import sys
from StringIO import StringIO
from feedplatform import test as feedev
from feedplatform import log

tests_run = 0

class Feed1(feedev.Feed):
    content = ""
    def pass1(feed):
        global tests_run
        tests_run += 1

    def pass5(feed):
        global tests_run
        tests_run += 1

class Feed2(feedev.Feed):
    content = ""
    def pass1(feed):
        global tests_run
        tests_run += 1

    def pass199(feed):
        global tests_run
        tests_run += 1


def test_all_handlers_are_called():
    try:
        feedev.testmod()
    finally:
        assert tests_run == 4


def test_log_output_is_captured():
    """Make sure the dev sees the log generated by the library if a
    test fails.
    """

    old_stdout = sys.stdout
    sys.stdout = StringIO()
    try:
        log.reset()

        feedev.testmod()
        sys.stdout.seek(0)
        stdout = sys.stdout.read()
    finally:
        sys.stdout = old_stdout
        log.reset()

    print "stdout was: ", stdout    # already goes to nose again
    assert 'Updating feed #1' in stdout